### ISSUE TITLE
rev_C

### ISSUE THREAD

**Issue by KennyLi** [DenChen11214/MilkThenCereal#1]
Good layout, but we think that there will be some issues with your layout/cleanliness of UI if you display every game's stats when you hover a category (i.e. not enough room to display every single DS game).

Our proposed solution to this dilemma of epic proportions is to only display critics scores and such when you hover over a game. 

Also, be careful with the font sizing because it may be hard to find a balance between being able to read what each category is labeled and having overlapping labels--an issue we saw with the sunburst chart you linked.

**Comment by DenChen11214** [comment]
We agree that there will not be enough room for every game in each platform, so we will most likely not include a majority of the games on the pie chart. As for the information that pops up when the user hovers a game, I don't think space will be a problem, since it will be replaced when the user hovers over a different game. We will keep the issue with font sizing in mind when creating our pie chart.
