### ISSUE TITLE
rev_D

### ISSUE THREAD

**Issue by jason-tung** [DenChen11214/MilkThenCereal#4]
I'm not sure how actionable this is, but maybe you can take user input and try to predict metrics based on some inputted statistics given by the user.

In addition, I think it would very **quite neat** to be able to compare games directly side by side without them having to be under the same category. Perhaps a filterable table?

**Comment by DenChen11214** [comment]
The filterable table does seem like a good way for the user to view and compare individual statistics as compared to grouping games together. We will keep this in mind and try to achieve it if we have time. As for the first suggestion, I don't think that we will do that, since it seems like a stretch goal that we wouldn't have time for.
